### ISSUE TITLE
Add drive path calculator

### ISSUE THREAD

**Issue by KaoruNishikawa** [necst-telescope/neclib#126]
**Motivation**

- To support scan observation and reserve room for implementation of more complex drive

**What should be realised**

```python
>>> finder = PathFinder()
>>> otf_path = finder.linear(from=(lon, lat), to=(lon, lat), frame="fk5", unit="deg", speed=1/6)
>>> type(otf_path)
(Quantity, Quantity, List[float])  # (Az, El, t)
```

**Comment by Kirby1717** [comment]
>>> finder = PathFinder() #クラス名
>>> otf_path = finder.linear(from=(lon, lat), to=(lon, lat), frame="fk5", unit="deg", speed=1/6)
>>> type(otf_path)
(Quantity, Quantity, List[float])  # (Az, El, t)
convert.py と同じ階層に別ファイルで
