### ISSUE TITLE
Add pointing error corrector

### ISSUE THREAD

**Issue by KaoruNishikawa** [necst-telescope/neclib#4]
This includes parameter file parser.
It's critically important to clarify whether the derived parameter is to be added or subtracted.

**Comment by KaoruNishikawa** [comment]
> It's critically important to clarify whether the derived parameter is to be added or subtracted.

To achieve this, the script should provide `apparent2refracted` and `refracted2apparent` methods (the terms may change).

**Comment by TakeruNishioka** [comment]
- 変数名を分かりやすく
- 数式が正しいか確認
- dx,dyでは無く、Az, elにそれらを反映したものを返すようにする
- ドキュメント作成（そこまで急がない）

**Comment by KaoruNishikawa** [comment]
@TakeruNishioka 
`N-CONST` is now importable after executing `poetry install`.
Please test if the function works, then create a pull-request.

**Comment by KaoruNishikawa** [comment]
@TakeruNishioka 
The structure of this package has significantly changed in #59.
The parameter file parser has also implemented in this package, with a little modification from [n_const.PointingError](https://nanten2.github.io/N-CONST/_source/n_const.pointing.html#n_const.pointing.PointingError), and the renewed version can directly be accessed from its subclass `neclib.parameters.pointing_error.PointingError`.
Could you please implement the coordinate conversion functionalities at `neclib.parameters.pointing_error.py`?

<details><summary>Japanese ver.</summary>

#59 でパッケージ構造が変更されました。
パラメータファイルの読み込みは今まで [n_const.PointingError](https://nanten2.github.io/N-CONST/_source/n_const.pointing.html#n_const.pointing.PointingError) を使っていたと思いますが、`neclib.parameters.parser.pointing_error_data.PointingErrorData` に再実装したのでこちらを使ってください。パラメータ名に若干の変更があるので注意してください。
読み込まれたパラメータは `PointingErrorData` を継承した `neclib.parameters.pointing_error.PointingError` からインスタンス変数として直接参照できます。
座標変換の機能を `neclib.parameters.pointing_error.py` に実装してもらってもよろしいでしょうか？

</details>
